#!/bin/bash

# ============================================================
# 🚀 UPI Tracker - GitHub Push Script
# GitHub Username: harishmani02-dotcom
# Repo Name: india-upi-tracker (Private)
# ============================================================

echo "============================================"
echo "  💸 UPI Tracker → GitHub Push Script"
echo "============================================"
echo ""

# ── STEP 1: Ask for GitHub Personal Access Token ──
echo "🔑 You need a GitHub Personal Access Token (PAT)"
echo ""
echo "   How to get one:"
echo "   1. Go to https://github.com/settings/tokens"
echo "   2. Click 'Generate new token (classic)'"
echo "   3. Give it a name: upi-tracker-push"
echo "   4. Select scopes: ✅ repo (full control)"
echo "   5. Click 'Generate token'"
echo "   6. COPY the token (it shows only once!)"
echo ""
read -sp "   Paste your GitHub Token here: " GITHUB_TOKEN
echo ""
echo ""

GITHUB_USER="harishmani02-dotcom"
REPO_NAME="india-upi-tracker"
PROJECT_DIR="$(dirname "$0")/UPITracker"

# ── STEP 2: Create the private repo on GitHub ──
echo "📁 Creating private repository '$REPO_NAME' on GitHub..."
CREATE_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
  -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/user/repos \
  -d "{
    \"name\": \"$REPO_NAME\",
    \"description\": \"💸 UPI Payment Tracker - Made for India 🇮🇳 | Track GPay, PhonePe, Paytm, BHIM transactions\",
    \"private\": true,
    \"auto_init\": false
  }")

if [ "$CREATE_RESPONSE" = "201" ]; then
  echo "   ✅ Repository created successfully!"
elif [ "$CREATE_RESPONSE" = "422" ]; then
  echo "   ⚠️  Repository already exists — will push to existing repo."
else
  echo "   ❌ Error creating repo (HTTP $CREATE_RESPONSE). Check your token."
  exit 1
fi

echo ""

# ── STEP 3: Initialize Git in project folder ──
echo "🗂️  Setting up Git in project folder..."
cd "$PROJECT_DIR" || { echo "❌ UPITracker folder not found next to this script!"; exit 1; }

git init
git config user.name "harishmani02-dotcom"
git config user.email "harishmani02@users.noreply.github.com"

# ── STEP 4: Create .gitignore ──
echo "📝 Creating Android .gitignore..."
cat > .gitignore << 'EOF'
# Built application files
*.apk
*.aar
*.ap_
*.aab

# Files for the ART/Dalvik VM
*.dex

# Java class files
*.class

# Generated files
bin/
gen/
out/
release/

# Gradle files
.gradle/
build/

# Local configuration file (sdk path, etc)
local.properties

# Proguard folder generated by Eclipse
proguard/

# Log Files
*.log

# Android Studio Navigation editor temp files
.navigation/

# Android Studio captures folder
captures/

# IntelliJ
*.iml
.idea/workspace.xml
.idea/tasks.xml
.idea/gradle.xml
.idea/assetWizardSettings.xml
.idea/dictionaries
.idea/libraries
.idea/caches
.idea/modules.xml
.idea/

# Keystore files (NEVER commit these!)
*.jks
*.keystore

# External native build folder generated in Android Studio 2.2 and later
.externalNativeBuild
.cxx/

# Google Services (e.g. APIs or Firebase)
google-services.json

# Freeline
freeline.py
freeline/
freeline_project_description.json

# fastlane
fastlane/report.xml
fastlane/Preview.html
fastlane/screenshots
fastlane/test_output
fastlane/readme.md

# Version control
vcs.xml

# lint
lint/intermediates/
lint/generated/
lint/outputs/
lint/tmp/
EOF

# ── STEP 5: Create README.md ──
echo "📖 Creating README.md..."
cat > README.md << 'EOF'
# 💸 India UPI Tracker

> **आपके पैसों का हिसाब** — Track all your UPI payments in one place!

![Android](https://img.shields.io/badge/Platform-Android-green?logo=android)
![Kotlin](https://img.shields.io/badge/Language-Kotlin-purple?logo=kotlin)
![Min SDK](https://img.shields.io/badge/Min%20SDK-24%20(Android%207)-blue)
![Made in India](https://img.shields.io/badge/Made%20with%20❤️-India-orange)

---

## 📱 Features

| Feature | Description |
|---------|-------------|
| 💸 Dashboard | Monthly spent & received summary in ₹ |
| 🏷️ Categories | 11 categories: Food, Transport, Shopping, Bills… |
| 📊 Reports | Pie chart spending breakdown |
| 🎯 Budget | Set monthly limits per category |
| 🔍 Search | Find any transaction instantly |
| 📱 Auto SMS | Auto-detect UPI transactions from bank SMS |
| 🔒 Private | All data stored locally — no internet needed |

---

## 🏦 Supported UPI Apps

- Google Pay (GPay)
- PhonePe
- Paytm
- BHIM
- Amazon Pay
- WhatsApp Pay

---

## 🛠️ Tech Stack

- **Language:** Kotlin
- **Database:** Room (SQLite)
- **Architecture:** MVVM + LiveData + ViewModel
- **Charts:** MPAndroidChart
- **UI:** Material Design 3

---

## 🚀 Build Instructions

See [BUILD_INSTRUCTIONS.md](BUILD_INSTRUCTIONS.md) for full steps to generate APK & AAB.

### Quick Start
```bash
# Clone the repo
git clone https://github.com/harishmani02-dotcom/india-upi-tracker.git

# Open in Android Studio
# Build → Generate Signed Bundle / APK
```

---

## 📂 Project Structure

```
app/src/main/java/com/india/upitracker/
├── model/          ← Transaction, Budget, Category enums
├── data/           ← Room DB, DAOs, Repository
├── ui/             ← Activities, Adapters, ViewModel
└── utils/          ← SMS Receiver, Currency Formatter
```

---

## 📲 Screens

- 🟠 **Splash** — Logo + Hindi tagline
- 🏠 **Home** — Monthly summary + recent transactions
- ➕ **Add Transaction** — Manual entry with all details
- 📊 **Reports** — Pie chart + category breakdown
- 🎯 **Budget** — Set/view monthly budgets
- 🔍 **Search** — Full-text transaction search
- 📋 **Detail** — Full transaction info + delete

---

## 🇮🇳 Made with ❤️ for India

*Helping 500+ crore UPI users track their money*

---

## 📄 License

MIT License — free to use and modify.
EOF

# ── STEP 6: Stage all files ──
echo "📦 Staging all project files..."
git add .
git status --short

# ── STEP 7: Initial commit ──
echo ""
echo "💬 Creating initial commit..."
git commit -m "🚀 Initial commit: UPI Tracker Android App

✨ Features:
- Monthly UPI spending dashboard (₹ formatted)
- 11 spending categories with emojis
- Room database (local, no internet needed)
- MVVM architecture with LiveData
- Pie chart reports (MPAndroidChart)
- Monthly budget planner
- SMS auto-detection for GPay/PhonePe/Paytm/BHIM
- Full-text transaction search
- Material Design 3 UI

🇮🇳 Made for India — आपके पैसों का हिसाब"

# ── STEP 8: Set remote and push ──
echo ""
echo "🌐 Connecting to GitHub..."
git branch -M main
git remote add origin "https://$GITHUB_TOKEN@github.com/$GITHUB_USER/$REPO_NAME.git"

echo "⬆️  Pushing to GitHub..."
git push -u origin main

echo ""
echo "============================================"
echo "  ✅ SUCCESS! Your app is on GitHub!"
echo "============================================"
echo ""
echo "  🔗 View your repo:"
echo "  https://github.com/$GITHUB_USER/$REPO_NAME"
echo ""
echo "  📁 Files pushed: $(git ls-files | wc -l) files"
echo "============================================"
